# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         yagg
version:      1.00
version_from: yagg
installdirs:  site
requires:
    File::Temp:                    0
    Getopt::Std:                   0
    Parse::Yapp::Driver:           1.05
    Storable:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
